### PR TITLE
[#2328] bugfix: renamed bcrypt algo name so it's usable, refactored algo name…

### LINKED ISSUE #2328: [Bug] BCrypt algorithm is not usable because it's mis-named
### Search before asking

- [x] I had searched in the [issues, **including closed issues**](https://github.com/apache/shiro/issues?q=is%3Aissue) and found no similar issues.

### Environment

BCrypt algo names are "2y" "2b" etc. They should be "bcrypt2y" and similar. The cryptic naming makes this algorithm ususable

### Shiro version

2.0.0 and later

### What was the actual outcome?

bcrypt algorithms should be usable

### What was the expected outcome?

N/A

### How to reproduce

N/A

### Debug logs

_No response_

### PR DESCRIPTION
**Pull request by lprimak**
… handling
fixes #2328

Following this checklist to help us incorporate your contribution quickly and easily:

 - [x] Make sure there is a [GitHub issue](https://github.com/apache/shiro/issues) filed
       for the change (usually before you start working on it).  Trivial changes like typos do not
       require a GitHub issue.  Your pull request should address just this issue, without pulling in other changes.
 - [x] Each commit in the pull request should have a meaningful subject line and body.
 - [x] Format the pull request title like `[#XXX] - Fixes bug in SessionManager`,
       where you replace `#XXX` with the appropriate GitHub issue. Best practice
       is to use the GitHub issue title in the pull request title and in the first line of the commit message.
 - [x] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
 - [x] add `fixes #XXX` if merging the PR should close a related issue.
 - [x] Run `mvn verify` to make sure basic checks pass. A more thorough check will be performed on your pull request automatically.
 - [x] If you have a group of commits related to the same change, please squash your commits into one and force push your branch using `git rebase -i`.
 - [x] Committers: Make sure a milestone is set on the PR

Trivial changes like typos do not require a GitHub issue (javadoc, comments...).
In this case, just format the pull request title like `[DOC] - Add javadoc in SessionManager`.

If this is your first contribution, you have to read the [Contribution Guidelines](https://github.com/apache/shiro/blob/master/CONTRIBUTING.md)

If your pull request is about ~20 lines of code you don't need to sign an [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf)
if you are unsure please ask on the developers list.

To make clear that you license your contribution under the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)
you have to acknowledge this by using the following check-box.

 - [x] I hereby declare this contribution to be licenced under the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)
 - [x] In any other case, please file an [Apache Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

### CODE REVIEW

**Comment by lprimak** [comment]
I believe the changed code should satisfy your concerns.

File: tools/hasher/src/main/java/org/apache/shiro/tools/hasher/Hasher.java [hunk 1]
```diff
@@ -70,7 +70,7 @@ public final class Hasher {
     private static final Logger LOG = LoggerFactory.getLogger(Hasher.class);
 
     private static final String HEX_PREFIX = "0x";
-    private static final String DEFAULT_ALGORITHM_NAME = "MD5";
+    private static final String DEFAULT_ALGORITHM_NAME = "SHA-256";
```
Comment (bmarwell) [inline tools/hasher/src/main/java/org/apache/shiro/tools/hasher/Hasher.java]: We need to document this on shiro-site.

**Review by bmarwell — APPROVED** [review]
Approved, with a question left.

File: tools/hasher/src/main/java/org/apache/shiro/tools/hasher/Hasher.java (hunk 1 above)
Comment (lprimak) [reply tools/hasher/src/main/java/org/apache/shiro/tools/hasher/Hasher.java]: Done. See https://github.com/apache/shiro-site/pull/249
